services:
  oidc:
    image: ghcr.io/soluto/oidc-server-mock:0.6.0
    container_name: cads-oidc-mock
    ports:
      - "5557:80"
    environment:
      ISSUER: http://cads-oidc-mock
      PORT: 80
      USERS_CONFIGURATION_PATH: /data/users.yml
      CLIENTS_CONFIGURATION_PATH: /data/clients.yml
      SCOPES_CONFIGURATION_PATH: /data/scopes.yml
      API_SCOPES_INLINE: |
        - Name: "reports.read"
          DisplayName: "Read reports"
      API_RESOURCES_INLINE: |
        - Name: "api://local-cads-cds"
          Scopes: ["reports.read"]
          UserClaims:
            - "email"
            - "name"
            - "preferred_username"
            - "role"
      SERVER_OPTIONS_INLINE: |
        {
          "IssuerUri": "http://cads-oidc-mock",
          "AccessTokenJwtType": "JWT",
          "Discovery": { "ShowKeySet": true },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          },
          "Events": {
            "RaiseErrorEvents": true,
            "RaiseSuccessEvents": true,
            "RaiseInformationEvents": true
          }
        }
    volumes:
      - ${ROOT_DIR}/oidc/config:/data
    networks:
      - cads-tools
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80/.well-known/openid-configuration"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  cads-tools:
    name: cads-tools
    driver: bridge