- ClientId: "local-cads-mis"
  ClientSecrets:
    - "local-mock-secret"
  AllowedGrantTypes:
    - "authorization_code"
  RequirePkce: false
  RedirectUris: ["http://localhost:3000", "http://localhost:3000/auth/callback", "http://localhost:3000/auth/sign-out", "http://localhost:3000/auth/signed-out", "https://oauth.pstmn.io/v1/callback", "http://localhost:7777/callback"]
  PostLogoutRedirectUris:
    - "http://localhost:3000/"
  AllowedScopes:
    - "openid"
    - "profile"
    - "email"
    - "offline_access"
    - "reports.read"
  AllowOfflineAccess: true
  AllowAccessTokensViaBrowser: true
  AccessTokenType: "Jwt"
  AlwaysSendClientClaims: true
  AlwaysIncludeUserClaimsInIdToken: true
  ClientClaimsPrefix: ""
- ClientId: "local-cads-api-client"
  ClientSecrets:
    - "local-mock-secret"
  AllowedGrantTypes:
    - "client_credentials"
  AllowedScopes:
    - "reports.read"
  AccessTokenType: "Jwt"
  AlwaysSendClientClaims: true
  ClientClaimsPrefix: ""
- ClientId: "local-cads-test-user-client"
  ClientSecrets:
    - "local-mock-secret"
  AllowedGrantTypes:
    - "password"
  AllowedScopes:
    - "openid"
    - "profile"
    - "email"
    - "reports.read"
  AccessTokenType: "Jwt"
  AlwaysSendClientClaims: true
  AlwaysIncludeUserClaimsInIdToken: true
  ClientClaimsPrefix: ""
- ClientId: "jt-ci-cads-mis"
  ClientSecrets:
    - "jt-ci-mock-secret"
  AllowedGrantTypes:
    - "authorization_code"
  RequirePkce: false
  RedirectUris: ["http://cads-mis:3000", "http://cads-mis:3000/auth/callback", "http://cads-mis:3000/auth/sign-out", "http://cads-mis:3000/auth/signed-out"]
  PostLogoutRedirectUris:
    - "http://cads-mis:3000/"
  AllowedScopes:
    - "openid"
    - "profile"
    - "email"
    - "offline_access"
    - "reports.read"
  AllowOfflineAccess: true
  AllowAccessTokensViaBrowser: true
  AccessTokenType: "Jwt"
  AlwaysSendClientClaims: true
  AlwaysIncludeUserClaimsInIdToken: true
  ClientClaimsPrefix: ""