- Name: "reports.read"
  DisplayName: "Read reports"
- Name: "db.admin.execute"
  DisplayName: "Execute DB admin commands"
- Name: "admin.s3.manager"
  DisplayName: "Manage S3 administration tasks"
- Name: "admin.queue.manager"
  DisplayName: "Manage queue administration tasks"
- Name: "openid"
  DisplayName: "OpenID"
- Name: "profile"
  DisplayName: "User profile"
- Name: "email"
  DisplayName: "Email"