- SubjectId: "787553ae-4c55-4b42-aafc-633274691cc1"
  Username: "mip-viewer-user"
  Password: "password"
  Claims:
    - Type: "name"
      Value: "Test MIP Viewer"
    - Type: "email"
      Value: "mip-viewer-user@internal.test"
    - Type: "preferred_username"
      Value: "mip-viewer-user"
    - Type: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
      Value: "mip-viewer"
- SubjectId: "bb054d87-3cf7-4809-beaf-42b0cdc2e419"
  Username: "db-admin-user"
  Password: "password"
  Claims:
    - Type: "name"
      Value: "Test DB Admin"
    - Type: "email"
      Value: "db-admin-user@internal.test"
    - Type: "preferred_username"
      Value: "db-admin-user"
    - Type: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
      Value: "cads-admin-superuser"